# Generated by Django 5.0.3 on 2024-03-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="song",
            name="author",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="favorites",
        ),
        migrations.RemoveField(
            model_name="song",
            name="audio",
        ),
        migrations.RemoveField(
            model_name="song",
            name="date",
        ),
        migrations.AddField(
            model_name="folder",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="file",
            field=models.FileField(
                default="sampleHappyMusic.mp3", upload_to="music_tracks/"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="song",
            name="genre",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
